export const toolboxConfig = {
    kind: 'categoryToolbox',
    contents: [
        {
            kind: 'category',
            name: 'Движение',
            categorystyle: 'motion_category',
            contents: [
                { kind: 'block', type: 'motion_movesteps', inputs: { STEPS: { shadow: { type: 'math_number', fields: { NUM: 10 } } } } },
                { kind: 'block', type: 'motion_turnright', inputs: { DEGREES: { shadow: { type: 'math_number', fields: { NUM: 15 } } } } },
                { kind: 'block', type: 'motion_turnleft', inputs: { DEGREES: { shadow: { type: 'math_number', fields: { NUM: 15 } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'motion_goto' },
                { kind: 'block', type: 'motion_gotoxy', inputs: { X: { shadow: { type: 'math_number', fields: { NUM: 0 } } }, Y: { shadow: { type: 'math_number', fields: { NUM: 0 } } } } },
                { kind: 'block', type: 'motion_glideto', inputs: { SECS: { shadow: { type: 'math_number', fields: { NUM: 1 } } } } },
                { kind: 'block', type: 'motion_glidesecstoxy', inputs: { SECS: { shadow: { type: 'math_number', fields: { NUM: 1 } } }, X: { shadow: { type: 'math_number', fields: { NUM: 0 } } }, Y: { shadow: { type: 'math_number', fields: { NUM: 0 } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'motion_pointindirection', inputs: { DIRECTION: { shadow: { type: 'math_number', fields: { NUM: 90 } } } } },
                { kind: 'block', type: 'motion_pointtowards' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'motion_changexby', inputs: { DX: { shadow: { type: 'math_number', fields: { NUM: 10 } } } } },
                { kind: 'block', type: 'motion_setx', inputs: { X: { shadow: { type: 'math_number', fields: { NUM: 0 } } } } },
                { kind: 'block', type: 'motion_changeyby', inputs: { DY: { shadow: { type: 'math_number', fields: { NUM: 10 } } } } },
                { kind: 'block', type: 'motion_sety', inputs: { Y: { shadow: { type: 'math_number', fields: { NUM: 0 } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'motion_ifonedgebounce' },
                { kind: 'block', type: 'motion_setrotationstyle' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'motion_xposition' },
                { kind: 'block', type: 'motion_yposition' },
                { kind: 'block', type: 'motion_direction' },
            ],
        },
        {
            kind: 'category',
            name: 'Внешний вид',
            categorystyle: 'looks_category',
            contents: [
                { kind: 'block', type: 'looks_sayforsecs', inputs: { MESSAGE: { shadow: { type: 'text', fields: { TEXT: 'Привет!' } } }, SECS: { shadow: { type: 'math_number', fields: { NUM: 2 } } } } },
                { kind: 'block', type: 'looks_say', inputs: { MESSAGE: { shadow: { type: 'text', fields: { TEXT: 'Привет!' } } } } },
                { kind: 'block', type: 'looks_thinkforsecs', inputs: { MESSAGE: { shadow: { type: 'text', fields: { TEXT: 'Хмм...' } } }, SECS: { shadow: { type: 'math_number', fields: { NUM: 2 } } } } },
                { kind: 'block', type: 'looks_think', inputs: { MESSAGE: { shadow: { type: 'text', fields: { TEXT: 'Хмм...' } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'looks_switchcostumeto' },
                { kind: 'block', type: 'looks_nextcostume' },
                { kind: 'block', type: 'looks_switchbackdropto' },
                { kind: 'block', type: 'looks_nextbackdrop' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'looks_changesizeby', inputs: { CHANGE: { shadow: { type: 'math_number', fields: { NUM: 10 } } } } },
                { kind: 'block', type: 'looks_setsizeto', inputs: { SIZE: { shadow: { type: 'math_number', fields: { NUM: 100 } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'looks_changeeffectby', inputs: { CHANGE: { shadow: { type: 'math_number', fields: { NUM: 25 } } } } },
                { kind: 'block', type: 'looks_seteffectto', inputs: { VALUE: { shadow: { type: 'math_number', fields: { NUM: 0 } } } } },
                { kind: 'block', type: 'looks_cleargraphiceffects' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'looks_show' },
                { kind: 'block', type: 'looks_hide' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'looks_gotofrontback' },
                { kind: 'block', type: 'looks_goforwardbackwardlayers', inputs: { NUM: { shadow: { type: 'math_number', fields: { NUM: 1 } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'looks_costumenumbername' },
                { kind: 'block', type: 'looks_backdropnumbername' },
                { kind: 'block', type: 'looks_size' },
            ],
        },
        {
            kind: 'category',
            name: 'Звук',
            categorystyle: 'sound_category',
            contents: [
                { kind: 'block', type: 'sound_playuntildone' },
                { kind: 'block', type: 'sound_play' },
                { kind: 'block', type: 'sound_stopallsounds' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'sound_changeeffectby', inputs: { VALUE: { shadow: { type: 'math_number', fields: { NUM: 10 } } } } },
                { kind: 'block', type: 'sound_seteffectto', inputs: { VALUE: { shadow: { type: 'math_number', fields: { NUM: 100 } } } } },
                { kind: 'block', type: 'sound_cleareffects' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'sound_changevolumeby', inputs: { VOLUME: { shadow: { type: 'math_number', fields: { NUM: -10 } } } } },
                { kind: 'block', type: 'sound_setvolumeto', inputs: { VOLUME: { shadow: { type: 'math_number', fields: { NUM: 100 } } } } },
                { kind: 'block', type: 'sound_volume' },
            ],
        },
        {
            kind: 'category',
            name: 'События',
            categorystyle: 'event_category',
            contents: [
                { kind: 'block', type: 'event_whenflagclicked' },
                { kind: 'block', type: 'event_whenkeypressed' },
                { kind: 'block', type: 'event_whenthisspriteclicked' },
                { kind: 'block', type: 'event_whenstageclicked' },
                { kind: 'block', type: 'event_whenbackdropswitchesto' },
                { kind: 'block', type: 'event_whengreaterthan', inputs: { VALUE: { shadow: { type: 'math_number', fields: { NUM: 10 } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'event_whenbroadcastreceived' },
                { kind: 'block', type: 'event_broadcast' },
                { kind: 'block', type: 'event_broadcastandwait' },
            ],
        },
        {
            kind: 'category',
            name: 'Управление',
            categorystyle: 'control_category',
            contents: [
                { kind: 'block', type: 'control_wait', inputs: { DURATION: { shadow: { type: 'math_number', fields: { NUM: 1 } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'control_repeat', inputs: { TIMES: { shadow: { type: 'math_number', fields: { NUM: 10 } } } } },
                { kind: 'block', type: 'control_forever' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'control_if' },
                { kind: 'block', type: 'control_if_else' },
                { kind: 'block', type: 'control_wait_until' },
                { kind: 'block', type: 'control_repeat_until' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'control_stop' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'control_start_as_clone' },
                { kind: 'block', type: 'control_create_clone_of' },
                { kind: 'block', type: 'control_delete_this_clone' },
            ],
        },
        {
            kind: 'category',
            name: 'Сенсоры',
            categorystyle: 'sensing_category',
            contents: [
                { kind: 'block', type: 'sensing_touchingobject' },
                { kind: 'block', type: 'sensing_touchingcolor' },
                { kind: 'block', type: 'sensing_coloristouchingcolor' },
                { kind: 'block', type: 'sensing_distanceto' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'sensing_askandwait', inputs: { QUESTION: { shadow: { type: 'text', fields: { TEXT: 'Как тебя зовут?' } } } } },
                { kind: 'block', type: 'sensing_answer' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'sensing_keypressed' },
                { kind: 'block', type: 'sensing_mousedown' },
                { kind: 'block', type: 'sensing_mousex' },
                { kind: 'block', type: 'sensing_mousey' },
                { kind: 'block', type: 'sensing_setdragmode' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'sensing_loudness' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'sensing_timer' },
                { kind: 'block', type: 'sensing_resettimer' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'sensing_of' },
                { kind: 'block', type: 'sensing_current' },
                { kind: 'block', type: 'sensing_dayssince2000' },
                { kind: 'block', type: 'sensing_username' },
            ],
        },
        {
            kind: 'category',
            name: 'Операторы',
            categorystyle: 'operator_category',
            contents: [
                { kind: 'block', type: 'operator_add', inputs: { NUM1: { shadow: { type: 'math_number', fields: { NUM: '' } } }, NUM2: { shadow: { type: 'math_number', fields: { NUM: '' } } } } },
                { kind: 'block', type: 'operator_subtract', inputs: { NUM1: { shadow: { type: 'math_number', fields: { NUM: '' } } }, NUM2: { shadow: { type: 'math_number', fields: { NUM: '' } } } } },
                { kind: 'block', type: 'operator_multiply', inputs: { NUM1: { shadow: { type: 'math_number', fields: { NUM: '' } } }, NUM2: { shadow: { type: 'math_number', fields: { NUM: '' } } } } },
                { kind: 'block', type: 'operator_divide', inputs: { NUM1: { shadow: { type: 'math_number', fields: { NUM: '' } } }, NUM2: { shadow: { type: 'math_number', fields: { NUM: '' } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'operator_random', inputs: { FROM: { shadow: { type: 'math_number', fields: { NUM: 1 } } }, TO: { shadow: { type: 'math_number', fields: { NUM: 10 } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'operator_gt' },
                { kind: 'block', type: 'operator_lt' },
                { kind: 'block', type: 'operator_equals' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'operator_and' },
                { kind: 'block', type: 'operator_or' },
                { kind: 'block', type: 'operator_not' },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'operator_join', inputs: { STRING1: { shadow: { type: 'text', fields: { TEXT: 'привет ' } } }, STRING2: { shadow: { type: 'text', fields: { TEXT: 'мир' } } } } },
                { kind: 'block', type: 'operator_letter_of', inputs: { LETTER: { shadow: { type: 'math_number', fields: { NUM: 1 } } }, STRING: { shadow: { type: 'text', fields: { TEXT: 'мир' } } } } },
                { kind: 'block', type: 'operator_length', inputs: { STRING: { shadow: { type: 'text', fields: { TEXT: 'мир' } } } } },
                { kind: 'block', type: 'operator_contains', inputs: { STRING1: { shadow: { type: 'text', fields: { TEXT: 'привет' } } }, STRING2: { shadow: { type: 'text', fields: { TEXT: 'при' } } } } },
                { kind: 'sep', gap: '24' },
                { kind: 'block', type: 'operator_mod', inputs: { NUM1: { shadow: { type: 'math_number', fields: { NUM: '' } } }, NUM2: { shadow: { type: 'math_number', fields: { NUM: '' } } } } },
                { kind: 'block', type: 'operator_round', inputs: { NUM: { shadow: { type: 'math_number', fields: { NUM: '' } } } } },
                { kind: 'block', type: 'operator_mathop', inputs: { NUM: { shadow: { type: 'math_number', fields: { NUM: '' } } } } },
            ],
        },
        {
            kind: 'category',
            name: 'Переменные',
            categorystyle: 'variable_category',
            custom: 'VARIABLE_DYNAMIC',
            contents: [
                { kind: 'button', text: 'Создать переменную', callbackKey: 'CREATE_VARIABLE' },
                { kind: 'block', type: 'data_variable' },
                { kind: 'block', type: 'data_setvariableto', inputs: { VALUE: { shadow: { type: 'math_number', fields: { NUM: 0 } } } } },
                { kind: 'block', type: 'data_changevariableby', inputs: { VALUE: { shadow: { type: 'math_number', fields: { NUM: 1 } } } } },
                { kind: 'block', type: 'data_showvariable' },
                { kind: 'block', type: 'data_hidevariable' },
                { kind: 'sep', gap: '24' },
                { kind: 'button', text: 'Создать список', callbackKey: 'CREATE_LIST' },
                { kind: 'block', type: 'data_addtolist', inputs: { ITEM: { shadow: { type: 'text', fields: { TEXT: 'элемент' } } } } },
                { kind: 'block', type: 'data_deleteoflist', inputs: { INDEX: { shadow: { type: 'math_number', fields: { NUM: 1 } } } } },
                { kind: 'block', type: 'data_deletealloflist' },
                { kind: 'block', type: 'data_insertatlist', inputs: { ITEM: { shadow: { type: 'text', fields: { TEXT: 'элемент' } } }, INDEX: { shadow: { type: 'math_number', fields: { NUM: 1 } } } } },
                { kind: 'block', type: 'data_replaceitemoflist', inputs: { INDEX: { shadow: { type: 'math_number', fields: { NUM: 1 } } }, ITEM: { shadow: { type: 'text', fields: { TEXT: 'элемент' } } } } },
                { kind: 'block', type: 'data_itemoflist', inputs: { INDEX: { shadow: { type: 'math_number', fields: { NUM: 1 } } } } },
                { kind: 'block', type: 'data_itemnumoflist', inputs: { ITEM: { shadow: { type: 'text', fields: { TEXT: 'элемент' } } } } },
                { kind: 'block', type: 'data_lengthoflist' },
                { kind: 'block', type: 'data_listcontainsitem', inputs: { ITEM: { shadow: { type: 'text', fields: { TEXT: 'элемент' } } } } },
                { kind: 'block', type: 'data_showlist' },
                { kind: 'block', type: 'data_hidelist' },
            ],
        },
        {
            kind: 'category',
            name: 'Другие блоки',
            categorystyle: 'procedure_category',
            contents: [
                { kind: 'button', text: 'Создать блок', callbackKey: 'CREATE_PROCEDURE' },
                { kind: 'block', type: 'procedures_definition' },
                { kind: 'block', type: 'procedures_call' },
            ],
        },
    ],
};